In [ ]:
#numpy-numerical python
! pip install numpy




In [1]:
import numpy as np
print(np.__version__)

1.23.5


In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr1 = np.array((1,2,3,4,5))
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#0D or Scalars

var = np.array(42)
print(var)
print(type(var))


42
<class 'numpy.ndarray'>


In [6]:
#1D or unidimensional array
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [11]:
#2D  or matrix
arr = np.array([[1,2,3,4],[1,2,3,45]])
print(arr)

[[ 1  2  3  4]
 [ 1  2  3 45]]


In [9]:
#3D aray or tensor
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[45,56,88]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [45 56 88]]]


In [12]:
a =  np.array(42)
b = np.array([1,2,3,4,5,6])
c = np.array([[1,2,3,4],[1,2,3,45]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[45,56,88]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
b = np.array([1,2,3,4,5,6],ndmin = 5)
print(b)
print(b.ndim)

[[[[[1 2 3 4 5 6]]]]]
5


In [14]:
b = np.array([1,2,3,4,5,6])
print(b[0])


1


In [15]:
print(b[-1])

6


In [16]:
print(b[0] + b[3])


5


In [20]:
c = np.array([[1,2,3,4],[1,2,3,45]])
print(c)
print(c[1,3])

[[ 1  2  3  4]
 [ 1  2  3 45]]
45


In [21]:
print(c[0,2])

3


In [22]:
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[45,56,88]]])
print(d)
print(d[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [45 56 88]]]
6


In [24]:
#slicing
a = np.array([1,2,3,4,5,6,4,7,8,9,4,10,12,3,4,5])
print(a[0:5])

[1 2 3 4 5]


In [26]:
print(a[3:])

[ 4  5  6  4  7  8  9  4 10 12  3  4  5]


In [27]:
print(a[:4])

[1 2 3 4]


In [28]:
print(c[-3:-1])

[[1 2 3 4]]


In [29]:
print(a[1:6:2])#[1,2,3,4,5,6,4,7,8,9,4,10,12,3,4,5])2,3,4,5,6

[2 4 6]


In [30]:
c = np.array([[1,2,3,4],[1,2,3,45]])
print(c[1,0:3])

[1 2 3]


In [31]:
print(c[0:2,2])

[3 3]


In [ ]:

#datatypes
string ---- S
integer--- i
float  -----f
blooean ----b
complex ----C
unicode string ----- U

In [32]:
b = np.array([1,2,3,4,5,6])
print(b.dtype)

int64


In [33]:
arr = np.array(["apple","orange","banana","cherry"])
print(arr.dtype)

<U6


In [34]:
b = np.array([1,2,3,4,5,6],dtype = "S")
print(b)
print(b.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [35]:
b = np.array([1,2,3,4,5,6])
newarr =  b.astype("f")
print(newarr)
print(newarr.dtype)


[1. 2. 3. 4. 5. 6.]
float32


In [36]:

newarr =  b.astype("int")
print(newarr)
print(newarr.dtype)

[1 2 3 4 5 6]
int64


In [37]:

newarr =  b.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True  True  True  True  True]
bool


In [38]:
var = np.array([1,2,3,4,5,6])
y = var.copy()
print(var)
print(y)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [41]:
var[0] = 100
print(var)
print(y)

[100   2   3   4   5   6]
[1 2 3 4 5 6]


In [42]:
var = np.array([1,2,3,4,5,6])
x = var.view()
print(var)
print(x)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [43]:
var[0] = 1000
print(var)
print(x)

[1000    2    3    4    5    6]
[1000    2    3    4    5    6]


In [ ]:

#list vs array
oD ----------Multi
any data type -----(any data type)single data type for single array
solw --- fast
remove,add -fast---method -professional
item side by side memory allocating -----------item side by side memory allocating


