In [2]:
#shape
import numpy as np
arr = np.array([[1,2,3,4,51],[1,2,3,4,5]])
print(arr)
print(arr.shape)

[[ 1  2  3  4 51]
 [ 1  2  3  4  5]]
(2, 5)


In [3]:
arr = np.array([1,2,3,4,5],ndmin = 5)

print(arr)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [5]:
#reshape
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
arr = np.array([[1,2,3,4,5],[11,22,33,44,55]])
new =arr.reshape(-1)
print(new)

[ 1  2  3  4  5 11 22 33 44 55]


In [9]:
arr = np.array([1,2,3,4,5,6])

for x in arr:
  print(x)

1
2
3
4
5
6


In [11]:
arr = np.array([[1,2,3,4,5],[11,22,33,44,55]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
11
22
33
44
55


In [15]:
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
for x in arr:
  for y in x:
    for z in y:
      print (z)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [16]:
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [20]:
arr = np.array([1,2,3,4,5,6])

for x in np.nditer(arr,flags = ['buffered'],op_dtypes=['S']):
  print(x.dtype)

|S21
|S21
|S21
|S21
|S21
|S21


In [21]:
arr = np.array([1,2,3,4,5,6])

for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


In [22]:
arr = np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])
for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(0, 5) 6
(1, 0) 11
(1, 1) 22
(1, 2) 33
(1, 3) 44
(1, 4) 55
(1, 5) 66


In [24]:
#join

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([11,12,13,14,15,16])


arr = np.concatenate((arr1,arr2))

print(arr)

[ 1  2  3  4  5  6 11 12 13 14 15 16]


In [26]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[11,22,33,44,55],[66,77,88,99,100]])


arr = np.concatenate((arr1,arr2),axis = 1)
print(arr1)
print(arr2)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 11  22  33  44  55]
 [ 66  77  88  99 100]]
[[  1   2   3   4   5  11  22  33  44  55]
 [  6   7   8   9  10  66  77  88  99 100]]


In [27]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([11,12,13,14,15,16])

arr = np.hstack((arr1,arr2))

print(arr)

[ 1  2  3  4  5  6 11 12 13 14 15 16]


In [29]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([11,12,13,14,15,16])

arr = np.vstack((arr1,arr2))

print(arr)

[[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]]


In [30]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([11,12,13,14,15,16])

arr = np.dstack((arr1,arr2))

print(arr)

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]
  [ 6 16]]]


In [32]:
arr1 = np.array([1,2,3,4,5,6])

new = np.array_split(arr1,3)
print(new)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [33]:
arr1 = np.array([1,2,3,4,5,6])

new = np.array_split(arr1,4)
print(new)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [34]:
print(new[0])
print(new[1])
print(new[2])

[1 2]
[3 4]
[5]


In [38]:
arr1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

new = np.hsplit(arr1,3)
print(new)

for i in new:
  print(i)

[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
[[1 2]
 [7 8]]
[[ 3  4]
 [ 9 10]]
[[ 5  6]
 [11 12]]


In [44]:
arr1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

new = np.vsplit(arr1,2)
print(new)

for i in new:
  print(i)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]
[[1 2 3 4 5 6]]
[[ 7  8  9 10 11 12]]


In [45]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.where(arr1 == 5)

print(x)


(array([4]),)


In [46]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.where(arr1%2 == 0)

print(x)


(array([1, 3, 5, 7]),)


In [47]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.where(arr1%2 == 1)

print(x)


(array([0, 2, 4, 6, 8]),)


In [48]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.searchsorted(arr1,5)

print(x)


4


In [50]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.searchsorted(arr1,5,side = 'right')

print(x)


5


In [51]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.searchsorted(arr1,[2,4,5])

print(x)

[1 3 4]


In [52]:
arr1 = np.array([4,9,8,2,3,1,6])
print(np.sort(arr1))

[1 2 3 4 6 8 9]


In [53]:
arr = np.array(["chery","banana","apple"])
print(np.sort(arr))

['apple' 'banana' 'chery']


In [54]:
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [55]:
arr = np.array([41,42,43,45,46,48])

x = [True,False,True,False,True,False]

newarr = arr[x]


print(newarr)


[41 43 46]


In [56]:
arr = np.array([41,42,43,45,46,48])

filter_arr = []

for elem in arr:

  if elem >43:
    filter_arr.append(True)
  else:
    filter_arr.append(False)


newarr = arr[filter_arr]

print(newarr)
print(filter_arr)


[45 46 48]
[False, False, False, True, True, True]


In [57]:
arr = np.array([41,42,43,45,46,48])
filter_arr = arr > 43
newarr = arr[filter_arr]

print(newarr)
print(filter_arr)


[45 46 48]
[False False False  True  True  True]


In [58]:
arr = np.array([41,42,43,45,46,48])

filter_arr = []

for elem in arr:

  if elem %2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)


newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, False, True, True]
[42 46 48]


In [59]:
arr = np.array([41,42,43,45,46,48])
filter_arr = arr %2 == 0
newarr = arr[filter_arr]

print(newarr)
print(filter_arr)

[42 46 48]
[False  True False False  True  True]


In [62]:
from numpy import random
x = random.randint(100)
print(x)

76


In [66]:
x = random.rand()
print(x)

0.4266048325156869


In [67]:
x = random.randint(100,size = (5))
print(x)

[40 60 40 30  9]


In [69]:
x = random.rand(5)
print(x)

[0.27615182 0.43084099 0.08724336 0.02616882 0.79038591]


In [70]:
x = random.randint(100,size = (2,5))
print(x)

[[ 1 70 22 47 68]
 [13 89 96 45  7]]


In [71]:
x = random.rand(2,5)
print(x)

[[0.25586204 0.27163986 0.46485184 0.66958516 0.47370404]
 [0.87757592 0.56331064 0.14560519 0.61566745 0.73042787]]


In [73]:
x = random.choice([3,4,5,6,7,8])

print(x)

4


In [74]:
x = random.choice([3,4,5,6,7,8],size = (3,5))

print(x)

[[4 8 7 4 6]
 [5 6 5 8 3]
 [7 4 4 5 4]]
